[package]
name = "debug_bitbox"
version = "0.1.0"
authors = ["Darren Kulp <darren@kulp.ch>"]
edition = "2018"

[dependencies]
bitvec = "*"

[patch.crates-io]
bitvec = { git = "https://github.com/myrrlyn/bitvec.git" }
